version: 0.1

phases:
  install:
    commands:
      - pip install --upgrade pip
      - pip install -r ./hello_world/requirements.txt -t hello_world/
      - zip -r hello_world.zip ./hello_world
      - zip -r authorizer.zip ./authorizer
      - ls -l
      - aws s3 cp ./ s3://testsamcicd/lambda/ --recursive  
  build:
    commands:
      - aws cloudformation package --template-file template.yaml --s3-bucket testsamcicd  --output-template-file packaged-template.yaml 
      - aws cloudformation deploy --stack-name announcement --capabilities CAPABILITY_IAM --template-file packaged-template.yaml --parameter-overrides "Stage=test"
artifacts:
  base-directory: assessment
  files:
    - '**/*'
  type: zip
