version = 0.1
[default.deploy.parameters]
stack_name = "Mytests3"
resolve_s3 = true
s3_prefix = "Mytests3"
region = "eu-north-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "Stage=\"dev\" SourceBucketName=\"mys3testlambdafile\""
image_repositories = []
